### ISSUE TITLE
Idea

### ISSUE THREAD

**Issue by chkngit** [ovichowdhury/holy-quran#1]
Salam.

I like the idea and would like to support the dev. I am just a c programming developer but willing to learn dapp lungage

**Comment by ovichowdhury** [comment]
A pleasure to hear from you. The project is a POC and the source code is open for all. you can fork the project and customize it or you can even write a completely new one on top of this concept. My suggestion would be to learn more about Blockchain and Ethereum so that you can work on this concept from scratch.
